
export interface RealSquadPlayer {
  name: string
  number: number
  position: string
}

export const realSquads: Record<string, RealSquadPlayer[]> = {
  // CONMEBOL
  "Argentina": [
    { "name": "Juan Musso", "number": 1, "position": "Portero" },
    { "name": "Marcos Senesi", "number": 2, "position": "Defensa" },
    { "name": "Nicolás Tagliafico", "number": 3, "position": "Defensa" },
    { "name": "Gonzalo Montiel", "number": 4, "position": "Defensa" },
    { "name": "Leandro Paredes", "number": 5, "position": "Mediocampista" },
    { "name": "Lisandro Martínez", "number": 6, "position": "Defensa" },
    { "name": "Rodrigo De Paul", "number": 7, "position": "Mediocampista" },
    { "name": "Valentín Barco", "number": 8, "position": "Mediocampista" },
    { "name": "Julián Alvarez", "number": 9, "position": "Delantero" },
    { "name": "Lionel Messi", "number": 10, "position": "Delantero" },
    { "name": "Giovani Lo Celso", "number": 11, "position": "Mediocampista" },
    { "name": "Gerónimo Rulli", "number": 12, "position": "Portero" },
    { "name": "Cristian Romero", "number": 13, "position": "Defensa" },
    { "name": "Exequiel Palacios", "number": 14, "position": "Mediocampista" },
    { "name": "Nicolás González", "number": 15, "position": "Mediocampista" },
    { "name": "Thiago Almada", "number": 16, "position": "Delantero" },
    { "name": "Giuliano Simeone", "number": 17, "position": "Delantero" },
    { "name": "Nico Paz", "number": 18, "position": "Delantero" },
    { "name": "Nicolás Otamendi", "number": 19, "position": "Defensa" },
    { "name": "Alexis Mac Allister", "number": 20, "position": "Mediocampista" },
    { "name": "José Manuel López", "number": 21, "position": "Delantero" },
    { "name": "Lautaro Martínez", "number": 22, "position": "Delantero" },
    { "name": "Emiliano Martínez", "number": 23, "position": "Portero" },
    { "name": "Enzo Fernández", "number": 24, "position": "Mediocampista" },
    { "name": "Facundo Medina", "number": 25, "position": "Defensa" },
    { "name": "Nahuel Molina", "number": 26, "position": "Defensa" }
  ],
  "Brasil": [
    { "name": "Alisson", "number": 1, "position": "Portero" },
    { "name": "Éderson Silva", "number": 2, "position": "Mediocampista" },
    { "name": "Gabriel Magalhães", "number": 3, "position": "Defensa" },
    { "name": "Marquinhos", "number": 4, "position": "Defensa" },
    { "name": "Casemiro", "number": 5, "position": "Mediocampista" },
    { "name": "Alex Sandro", "number": 6, "position": "Defensa" },
    { "name": "Vinícius Júnior", "number": 7, "position": "Delantero" },
    { "name": "Bruno Guimarães", "number": 8, "position": "Mediocampista" },
    { "name": "Matheus Cunha", "number": 9, "position": "Delantero" },
    { "name": "Neymar", "number": 10, "position": "Delantero" },
    { "name": "Raphinha", "number": 11, "position": "Delantero" },
    { "name": "Weverton", "number": 12, "position": "Portero" },
    { "name": "Danilo Luiz", "number": 13, "position": "Defensa" },
    { "name": "Bremer", "number": 14, "position": "Defensa" },
    { "name": "Léo Pereira", "number": 15, "position": "Defensa" },
    { "name": "Douglas Santos", "number": 16, "position": "Defensa" },
    { "name": "Fabinho", "number": 17, "position": "Mediocampista" },
    { "name": "Danilo Santos", "number": 18, "position": "Mediocampista" },
    { "name": "Endrick", "number": 19, "position": "Delantero" },
    { "name": "Lucas Paquetá", "number": 20, "position": "Mediocampista" },
    { "name": "Luiz Henrique", "number": 21, "position": "Delantero" },
    { "name": "Gabriel Martinelli", "number": 22, "position": "Delantero" },
    { "name": "Ederson Moraes", "number": 23, "position": "Portero" },
    { "name": "Roger Ibáñez", "number": 24, "position": "Defensa" },
    { "name": "Igor Thiago", "number": 25, "position": "Delantero" },
    { "name": "Rayan", "number": 26, "position": "Delantero" }
  ],
  "Colombia": [
    { "name": "David Ospina", "number": 1, "position": "Portero" },
    { "name": "Daniel Muñoz", "number": 2, "position": "Defensa" },
    { "name": "Jhon Lucumí", "number": 3, "position": "Defensa" },
    { "name": "Santiago Arias", "number": 4, "position": "Defensa" },
    { "name": "Kevin Castaño", "number": 5, "position": "Mediocampista" },
    { "name": "Richard Ríos", "number": 6, "position": "Mediocampista" },
    { "name": "Luis Díaz", "number": 7, "position": "Delantero" },
    { "name": "Jorge Carrascal", "number": 8, "position": "Mediocampista" },
    { "name": "Jhon Córdoba", "number": 9, "position": "Delantero" },
    { "name": "James Rodríguez", "number": 10, "position": "Mediocampista" },
    { "name": "Jhon Arias", "number": 11, "position": "Mediocampista" },
    { "name": "Camilo Vargas", "number": 12, "position": "Portero" },
    { "name": "Yerry Mina", "number": 13, "position": "Defensa" },
    { "name": "Gustavo Puerta", "number": 14, "position": "Defensa" },
    { "name": "Juan Portilla", "number": 15, "position": "Mediocampista" },
    { "name": "Jefferson Lerma", "number": 16, "position": "Mediocampista" },
    { "name": "Johan Mojica", "number": 17, "position": "Defensa" },
    { "name": "Willer Ditta", "number": 18, "position": "Defensa" },
    { "name": "Cucho Hernández", "number": 19, "position": "Delantero" },
    { "name": "Juan Fernando Quintero", "number": 20, "position": "Mediocampista" },
    { "name": "Jaminton Campaz", "number": 21, "position": "Delantero" },
    { "name": "Deiver Machado", "number": 22, "position": "Defensa" },
    { "name": "Davinson Sánchez", "number": 23, "position": "Defensa" },
    { "name": "Álvaro Montero", "number": 24, "position": "Portero" },
    { "name": "Luis Suárez", "number": 25, "position": "Delantero" },
    { "name": "Andrés Gómez", "number": 26, "position": "Delantero" }
  ],
  "Ecuador": [
    { "name": "Hernán Galíndez", "number": 1, "position": "Portero" },
    { "name": "Félix Torres", "number": 2, "position": "Defensa" },
    { "name": "Piero Hincapié", "number": 3, "position": "Defensa" },
    { "name": "Joel Ordóñez", "number": 4, "position": "Defensa" },
    { "name": "Jordy Alcívar", "number": 5, "position": "Mediocampista" },
    { "name": "Willian Pacho", "number": 6, "position": "Defensa" },
    { "name": "Pervis Estupiñán", "number": 7, "position": "Defensa" },
    { "name": "Anthony Valencia", "number": 8, "position": "Mediocampista" },
    { "name": "John Yeboah", "number": 9, "position": "Delantero" },
    { "name": "Kendry Páez", "number": 10, "position": "Mediocampista" },
    { "name": "Kevin Rodríguez", "number": 11, "position": "Delantero" },
    { "name": "Moisés Ramírez", "number": 12, "position": "Portero" },
    { "name": "Enner Valencia", "number": 13, "position": "Delantero" },
    { "name": "Alan Minda", "number": 14, "position": "Mediocampista" },
    { "name": "Pedro Vite", "number": 15, "position": "Mediocampista" },
    { "name": "Jordy Caicedo", "number": 16, "position": "Delantero" },
    { "name": "Ángelo Preciado", "number": 17, "position": "Defensa" },
    { "name": "Denil Castillo", "number": 18, "position": "Mediocampista" },
    { "name": "Gonzalo Plata", "number": 19, "position": "Delantero" },
    { "name": "Nilson Angulo", "number": 20, "position": "Delantero" },
    { "name": "Alan Franco", "number": 21, "position": "Mediocampista" },
    { "name": "Gonzalo Valle", "number": 22, "position": "Portero" },
    { "name": "Moisés Caicedo", "number": 23, "position": "Mediocampista" },
    { "name": "Jeremy Arévalo", "number": 24, "position": "Delantero" },
    { "name": "Jackson Porozo", "number": 25, "position": "Defensa" },
    { "name": "Yaimar Medina", "number": 26, "position": "Defensa" }
  ],
  "Paraguay": [
    { "name": "Gatito Fernández", "number": 1, "position": "Portero" },
    { "name": "Gustavo Velázquez", "number": 2, "position": "Defensa" },
    { "name": "Omar Alderete", "number": 3, "position": "Defensa" },
    { "name": "Juan José Cáceres", "number": 4, "position": "Defensa" },
    { "name": "Fabián Balbuena", "number": 5, "position": "Defensa" },
    { "name": "Júnior Alonso", "number": 6, "position": "Defensa" },
    { "name": "Ramón Sosa", "number": 7, "position": "Mediocampista" },
    { "name": "Diego Gómez", "number": 8, "position": "Mediocampista" },
    { "name": "Antonio Sanabria", "number": 9, "position": "Delantero" },
    { "name": "Miguel Almirón", "number": 10, "position": "Mediocampista" },
    { "name": "Maurício", "number": 11, "position": "Mediocampista" },
    { "name": "Orlando Gill", "number": 12, "position": "Portero" },
    { "name": "José Canale", "number": 13, "position": "Defensa" },
    { "name": "Andrés Cubas", "number": 14, "position": "Mediocampista" },
    { "name": "Gustavo Gómez", "number": 15, "position": "Defensa" },
    { "name": "Damián Bobadilla", "number": 16, "position": "Mediocampista" },
    { "name": "Kaku", "number": 17, "position": "Delantero" },
    { "name": "Álex Arce", "number": 18, "position": "Delantero" },
    { "name": "Julio Enciso", "number": 19, "position": "Delantero" },
    { "name": "Braian Ojeda", "number": 20, "position": "Mediocampista" },
    { "name": "Gabriel Ávalos", "number": 21, "position": "Delantero" },
    { "name": "Gastón Olveira", "number": 22, "position": "Portero" },
    { "name": "Matías Galarza", "number": 23, "position": "Mediocampista" },
    { "name": "Gustavo Caballero", "number": 24, "position": "Mediocampista" },
    { "name": "Isidro Pitta", "number": 25, "position": "Delantero" },
    { "name": "Alexandro Maidana", "number": 26, "position": "Defensa" }
  ],
  "Uruguay": [
    { "name": "Sergio Rochet", "number": 1, "position": "Portero" },
    { "name": "José María Giménez", "number": 2, "position": "Defensa" },
    { "name": "Sebastián Cáceres", "number": 3, "position": "Defensa" },
    { "name": "Ronald Araújo", "number": 4, "position": "Defensa" },
    { "name": "Manuel Ugarte", "number": 5, "position": "Mediocampista" },
    { "name": "Rodrigo Bentancur", "number": 6, "position": "Mediocampista" },
    { "name": "Nicolás de la Cruz", "number": 7, "position": "Mediocampista" },
    { "name": "Federico Valverde", "number": 8, "position": "Mediocampista" },
    { "name": "Darwin Núñez", "number": 9, "position": "Delantero" },
    { "name": "Giorgian de Arrascaeta", "number": 10, "position": "Mediocampista" },
    { "name": "Facundo Pellistri", "number": 11, "position": "Delantero" },
    { "name": "Santiago Mele", "number": 12, "position": "Portero" },
    { "name": "Guillermo Varela", "number": 13, "position": "Defensa" },
    { "name": "Agustín Canobbio", "number": 14, "position": "Mediocampista" },
    { "name": "Emiliano Martínez", "number": 15, "position": "Mediocampista" },
    { "name": "Mathías Olivera", "number": 16, "position": "Defensa" },
    { "name": "Matías Viña", "number": 17, "position": "Defensa" },
    { "name": "Brian Rodríguez", "number": 18, "position": "Delantero" },
    { "name": "Rodrigo Aguirre", "number": 19, "position": "Delantero" },
    { "name": "Maximiliano Araújo", "number": 20, "position": "Mediocampista" },
    { "name": "Federico Viñas", "number": 21, "position": "Delantero" },
    { "name": "Joaquín Piquerez", "number": 22, "position": "Mediocampista" },
    { "name": "Fernando Muslera", "number": 23, "position": "Portero" },
    { "name": "Santiago Bueno", "number": 24, "position": "Defensa" },
    { "name": "Juan Manuel Sanabria", "number": 25, "position": "Mediocampista" },
    { "name": "Rodrigo Zalazar", "number": 26, "position": "Mediocampista" }
  ],

  // UEFA
  "Alemania": [
    { "name": "Manuel Neuer", "number": 1, "position": "Portero" },
    { "name": "Antonio Rüdiger", "number": 2, "position": "Defensa" },
    { "name": "Waldemar Anton", "number": 3, "position": "Defensa" },
    { "name": "Jonathan Tah", "number": 4, "position": "Defensa" },
    { "name": "Aleksandar Pavlović", "number": 5, "position": "Mediocampista" },
    { "name": "Joshua Kimmich", "number": 6, "position": "Defensa" },
    { "name": "Kai Havertz", "number": 7, "position": "Delantero" },
    { "name": "Leon Goretzka", "number": 8, "position": "Mediocampista" },
    { "name": "Jamie Leweling", "number": 9, "position": "Mediocampista" },
    { "name": "Jamal Musiala", "number": 10, "position": "Mediocampista" },
    { "name": "Nick Woltemade", "number": 11, "position": "Delantero" },
    { "name": "Oliver Baumann", "number": 12, "position": "Portero" },
    { "name": "Pascal Groß", "number": 13, "position": "Mediocampista" },
    { "name": "Maximilian Beier", "number": 14, "position": "Delantero" },
    { "name": "Nico Schlotterbeck", "number": 15, "position": "Defensa" },
    { "name": "Angelo Stiller", "number": 16, "position": "Mediocampista" },
    { "name": "Florian Wirtz", "number": 17, "position": "Mediocampista" },
    { "name": "Nathaniel Brown", "number": 18, "position": "Defensa" },
    { "name": "Leroy Sané", "number": 19, "position": "Mediocampista" },
    { "name": "Nadiem Amiri", "number": 20, "position": "Mediocampista" },
    { "name": "Alexander Nübel", "number": 21, "position": "Portero" },
    { "name": "David Raum", "number": 22, "position": "Defensa" },
    { "name": "Felix Nmecha", "number": 23, "position": "Mediocampista" },
    { "name": "Malick Thiaw", "number": 24, "position": "Defensa" },
    { "name": "Assan Ouédraogo", "number": 25, "position": "Mediocampista" },
    { "name": "Deniz Undav", "number": 26, "position": "Delantero" }
  ],
  "Austria": [
    { "name": "Alexander Schlager", "number": 1, "position": "Portero" },
    { "name": "David Affengruber", "number": 2, "position": "Defensa" },
    { "name": "Kevin Danso", "number": 3, "position": "Defensa" },
    { "name": "Xaver Schlager", "number": 4, "position": "Mediocampista" },
    { "name": "Stefan Posch", "number": 5, "position": "Defensa" },
    { "name": "Nicolas Seiwald", "number": 6, "position": "Mediocampista" },
    { "name": "Marko Arnautović", "number": 7, "position": "Delantero" },
    { "name": "David Alaba", "number": 8, "position": "Defensa" },
    { "name": "Marcel Sabitzer", "number": 9, "position": "Mediocampista" },
    { "name": "Florian Grillitsch", "number": 10, "position": "Mediocampista" },
    { "name": "Michael Gregoritsch", "number": 11, "position": "Delantero" },
    { "name": "Florian Wiegele", "number": 12, "position": "Portero" },
    { "name": "Patrick Pentz", "number": 13, "position": "Portero" },
    { "name": "Saša Kalajdžić", "number": 14, "position": "Delantero" },
    { "name": "Philipp Lienhart", "number": 15, "position": "Defensa" },
    { "name": "Phillipp Mwene", "number": 16, "position": "Defensa" },
    { "name": "Carney Chukwuemeka", "number": 17, "position": "Mediocampista" },
    { "name": "Romano Schmid", "number": 18, "position": "Mediocampista" },
    { "name": "Dejan Ljubičić", "number": 19, "position": "Mediocampista" },
    { "name": "Konrad Laimer", "number": 20, "position": "Mediocampista" },
    { "name": "Patrick Wimmer", "number": 21, "position": "Delantero" },
    { "name": "Alexander Prass", "number": 22, "position": "Mediocampista" },
    { "name": "Marco Friedl", "number": 23, "position": "Defensa" },
    { "name": "Paul Wanner", "number": 24, "position": "Mediocampista" },
    { "name": "Michael Svoboda", "number": 25, "position": "Defensa" },
    { "name": "Alessandro Schöpf", "number": 26, "position": "Mediocampista" }
  ],
  "Bélgica": [
    { "name": "Thibaut Courtois", "number": 1, "position": "Portero" },
    { "name": "Zeno Debast", "number": 2, "position": "Defensa" },
    { "name": "Arthur Theate", "number": 3, "position": "Defensa" },
    { "name": "Brandon Mechele", "number": 4, "position": "Defensa" },
    { "name": "Maxim De Cuyper", "number": 5, "position": "Defensa" },
    { "name": "Axel Witsel", "number": 6, "position": "Mediocampista" },
    { "name": "Kevin De Bruyne", "number": 7, "position": "Mediocampista" },
    { "name": "Youri Tielemans", "number": 8, "position": "Mediocampista" },
    { "name": "Romelu Lukaku", "number": 9, "position": "Delantero" },
    { "name": "Leandro Trossard", "number": 10, "position": "Delantero" },
    { "name": "Jérémy Doku", "number": 11, "position": "Delantero" },
    { "name": "Senne Lammens", "number": 12, "position": "Portero" },
    { "name": "Mike Penders", "number": 13, "position": "Portero" },
    { "name": "Dodi Lukébakio", "number": 14, "position": "Delantero" },
    { "name": "Thomas Meunier", "number": 15, "position": "Defensa" },
    { "name": "Koni De Winter", "number": 16, "position": "Defensa" },
    { "name": "Charles De Ketelaere", "number": 17, "position": "Delantero" },
    { "name": "Joaquin Seys", "number": 18, "position": "Defensa" },
    { "name": "Diego Moreira", "number": 19, "position": "Mediocampista" },
    { "name": "Hans Vanaken", "number": 20, "position": "Mediocampista" },
    { "name": "Timothy Castagne", "number": 21, "position": "Defensa" },
    { "name": "Alexis Saelemaekers", "number": 22, "position": "Mediocampista" },
    { "name": "Nicolas Raskin", "number": 23, "position": "Mediocampista" },
    { "name": "Amadou Onana", "number": 24, "position": "Mediocampista" },
    { "name": "Nathan Ngoy", "number": 25, "position": "Defensa" },
    { "name": "Matias Fernandez-Pardo", "number": 26, "position": "Delantero" }
  ],
  "Bosnia y Herzegovina": [
    { "name": "Nikola Vasilj", "number": 1, "position": "Portero" },
    { "name": "Nihad Mujakinić", "number": 2, "position": "Defensa" },
    { "name": "Dennis Hadžikadunić", "number": 3, "position": "Defensa" },
    { "name": "Tarik Muharemović", "number": 4, "position": "Defensa" },
    { "name": "Sead Kolašinac", "number": 5, "position": "Defensa" },
    { "name": "Benjamin Tahirović", "number": 6, "position": "Mediocampista" },
    { "name": "Amar Dedić", "number": 7, "position": "Defensa" },
    { "name": "Armin Gigović", "number": 8, "position": "Mediocampista" },
    { "name": "Samed Baždar", "number": 9, "position": "Delantero" },
    { "name": "Ermedin Demirović", "number": 10, "position": "Delantero" },
    { "name": "Edin Džeko", "number": 11, "position": "Delantero" },
    { "name": "Mladen Jurkas", "number": 12, "position": "Portero" },
    { "name": "Ivan Bašić", "number": 13, "position": "Mediocampista" },
    { "name": "Ivan Šunjić", "number": 14, "position": "Mediocampista" },
    { "name": "Amar Memić", "number": 15, "position": "Mediocampista" },
    { "name": "Amir Hadžiahmetović", "number": 16, "position": "Mediocampista" },
    { "name": "Dženis Burnić", "number": 17, "position": "Mediocampista" },
    { "name": "Nikola Katić", "number": 18, "position": "Defensa" },
    { "name": "Kerim Alajbegović", "number": 19, "position": "Delantero" },
    { "name": "Esmir Bajraktarević", "number": 20, "position": "Delantero" },
    { "name": "Stjepan Radeljić", "number": 21, "position": "Defensa" },
    { "name": "Martin Zlomislić", "number": 22, "position": "Portero" },
    { "name": "Haris Tabaković", "number": 23, "position": "Delantero" },
    { "name": "Arjan Malić", "number": 24, "position": "Defensa" },
    { "name": "Jovo Lukić", "number": 25, "position": "Delantero" },
    { "name": "Ermin Mahmić", "number": 26, "position": "Mediocampista" }
  ],
  "Croacia": [
    { "name": "Dominik Livaković", "number": 1, "position": "Portero" },
    { "name": "Josip Stanišić", "number": 2, "position": "Defensa" },
    { "name": "Marin Pongračić", "number": 3, "position": "Defensa" },
    { "name": "Joško Gvardiol", "number": 4, "position": "Defensa" },
    { "name": "Duje Ćaleta-Car", "number": 5, "position": "Defensa" },
    { "name": "Josip Šutalo", "number": 6, "position": "Defensa" },
    { "name": "Nikola Moro", "number": 7, "position": "Mediocampista" },
    { "name": "Mateo Kovačić", "number": 8, "position": "Mediocampista" },
    { "name": "Andrej Kramarić", "number": 9, "position": "Delantero" },
    { "name": "Luka Modrić", "number": 10, "position": "Mediocampista" },
    { "name": "Ante Budimir", "number": 11, "position": "Delantero" },
    { "name": "Ivor Pandur", "number": 12, "position": "Portero" },
    { "name": "Nikola Vlašić", "number": 13, "position": "Mediocampista" },
    { "name": "Ivan Perišić", "number": 14, "position": "Delantero" },
    { "name": "Mario Pašalić", "number": 15, "position": "Mediocampista" },
    { "name": "Martin Baturina", "number": 16, "position": "Mediocampista" },
    { "name": "Petar Sučić", "number": 17, "position": "Mediocampista" },
    { "name": "Kristijan Jakić", "number": 18, "position": "Defensa" },
    { "name": "Toni Fruk", "number": 19, "position": "Mediocampista" },
    { "name": "Igor Matanović", "number": 20, "position": "Delantero" },
    { "name": "Luka Sučić", "number": 21, "position": "Mediocampista" },
    { "name": "Luka Vušković", "number": 22, "position": "Defensa" },
    { "name": "Dominik Kotarski", "number": 23, "position": "Portero" },
    { "name": "Marco Pašalić", "number": 24, "position": "Delantero" },
    { "name": "Martin Erlić", "number": 25, "position": "Defensa" },
    { "name": "Petar Musa", "number": 26, "position": "Delantero" }
  ],
  "España": [
    { "name": "David Raya", "number": 1, "position": "Portero" },
    { "name": "Marc Pubill", "number": 2, "position": "Defensa" },
    { "name": "Álex Grimaldo", "number": 3, "position": "Defensa" },
    { "name": "Eric García", "number": 4, "position": "Defensa" },
    { "name": "Marcos Llorente", "number": 5, "position": "Defensa" },
    { "name": "Mikel Merino", "number": 6, "position": "Mediocampista" },
    { "name": "Ferran Torres", "number": 7, "position": "Delantero" },
    { "name": "Fabián Ruiz", "number": 8, "position": "Mediocampista" },
    { "name": "Gavi", "number": 9, "position": "Mediocampista" },
    { "name": "Dani Olmo", "number": 10, "position": "Delantero" },
    { "name": "Yéremy Pino", "number": 11, "position": "Delantero" },
    { "name": "Pedro Porro", "number": 12, "position": "Defensa" },
    { "name": "Joan García", "number": 13, "position": "Portero" },
    { "name": "Aymeric Laporte", "number": 14, "position": "Defensa" },
    { "name": "Álex Baena", "number": 15, "position": "Mediocampista" },
    { "name": "Rodri", "number": 16, "position": "Mediocampista" },
    { "name": "Nico Williams", "number": 17, "position": "Delantero" },
    { "name": "Martín Zubimendi", "number": 18, "position": "Mediocampista" },
    { "name": "Lamine Yamal", "number": 19, "position": "Delantero" },
    { "name": "Pedri", "number": 20, "position": "Mediocampista" },
    { "name": "Mikel Oyarzabal", "number": 21, "position": "Delantero" },
    { "name": "Pau Cubarsí", "number": 22, "position": "Defensa" },
    { "name": "Unai Simón", "number": 23, "position": "Portero" },
    { "name": "Marc Cucurella", "number": 24, "position": "Defensa" },
    { "name": "Víctor Muñoz", "number": 25, "position": "Delantero" },
    { "name": "Borja Iglesias", "number": 26, "position": "Delantero" }
  ],
  "Escocia": [
    { "name": "Angus Gunn", "number": 1, "position": "Portero" },
    { "name": "Aaron Hickey", "number": 2, "position": "Defensa" },
    { "name": "Andy Robertson", "number": 3, "position": "Defensa" },
    { "name": "Scott McTominay", "number": 4, "position": "Mediocampista" },
    { "name": "Grant Hanley", "number": 5, "position": "Defensa" },
    { "name": "Kieran Tierney", "number": 6, "position": "Defensa" },
    { "name": "John McGinn", "number": 7, "position": "Mediocampista" },
    { "name": "Tyler Fletcher", "number": 8, "position": "Mediocampista" },
    { "name": "Lyndon Dykes", "number": 9, "position": "Delantero" },
    { "name": "Ché Adams", "number": 10, "position": "Delantero" },
    { "name": "Ryan Christie", "number": 11, "position": "Mediocampista" },
    { "name": "Liam Kelly", "number": 12, "position": "Portero" },
    { "name": "Jack Hendry", "number": 13, "position": "Defensa" },
    { "name": "Ross Stewart", "number": 14, "position": "Delantero" },
    { "name": "John Souttar", "number": 15, "position": "Defensa" },
    { "name": "Dominic Hyam", "number": 16, "position": "Defensa" },
    { "name": "Ben Gannon-Doak", "number": 17, "position": "Delantero" },
    { "name": "George Hirst", "number": 18, "position": "Delantero" },
    { "name": "Lewis Ferguson", "number": 19, "position": "Mediocampista" },
    { "name": "Lawrence Shankland", "number": 20, "position": "Delantero" },
    { "name": "Craig Gordon", "number": 21, "position": "Portero" },
    { "name": "Nathan Patterson", "number": 22, "position": "Defensa" },
    { "name": "Kenny McLean", "number": 23, "position": "Mediocampista" },
    { "name": "Anthony Ralston", "number": 24, "position": "Defensa" },
    { "name": "Findlay Curtis", "number": 25, "position": "Delantero" },
    { "name": "Scott McKenna", "number": 26, "position": "Defensa" }
  ],
  "Francia": [
    { "name": "Brice Samba", "number": 1, "position": "Portero" },
    { "name": "Malo Gusto", "number": 2, "position": "Defensa" },
    { "name": "Lucas Digne", "number": 3, "position": "Defensa" },
    { "name": "Dayot Upamecano", "number": 4, "position": "Defensa" },
    { "name": "Jules Koundé", "number": 5, "position": "Defensa" },
    { "name": "Manu Koné", "number": 6, "position": "Mediocampista" },
    { "name": "Ousmane Dembélé", "number": 7, "position": "Delantero" },
    { "name": "Aurélien Tchouaméni", "number": 8, "position": "Mediocampista" },
    { "name": "Marcus Thuram", "number": 9, "position": "Delantero" },
    { "name": "Kylian Mbappé", "number": 10, "position": "Delantero" },
    { "name": "Michael Olise", "number": 11, "position": "Delantero" },
    { "name": "Bradley Barcola", "number": 12, "position": "Delantero" },
    { "name": "N'Golo Kanté", "number": 13, "position": "Mediocampista" },
    { "name": "Adrien Rabiot", "number": 14, "position": "Mediocampista" },
    { "name": "Ibrahima Konaté", "number": 15, "position": "Defensa" },
    { "name": "Mike Maignan", "number": 16, "position": "Portero" },
    { "name": "William Saliba", "number": 17, "position": "Defensa" },
    { "name": "Warren Zaïre-Emery", "number": 18, "position": "Mediocampista" },
    { "name": "Théo Hernandez", "number": 19, "position": "Defensa" },
    { "name": "Désiré Doué", "number": 20, "position": "Delantero" },
    { "name": "Lucas Hernandez", "number": 21, "position": "Defensa" },
    { "name": "Jean-Philippe Mateta", "number": 22, "position": "Delantero" },
    { "name": "Robin Risser", "number": 23, "position": "Portero" },
    { "name": "Rayan Cherki", "number": 24, "position": "Mediocampista" },
    { "name": "Maghnes Akliouche", "number": 25, "position": "Mediocampista" },
    { "name": "Maxence Lacroix", "number": 26, "position": "Defensa" }
  ],
  "Países Bajos": [
    { "name": "Bart Verbruggen", "number": 1, "position": "Portero" },
    { "name": "Lutsharel Geertruida", "number": 2, "position": "Defensa" },
    { "name": "Marten de Roon", "number": 3, "position": "Mediocampista" },
    { "name": "Virgil van Dijk", "number": 4, "position": "Defensa" },
    { "name": "Nathan Aké", "number": 5, "position": "Defensa" },
    { "name": "Jan Paul van Hecke", "number": 6, "position": "Defensa" },
    { "name": "Justin Kluivert", "number": 7, "position": "Mediocampista" },
    { "name": "Ryan Gravenberch", "number": 8, "position": "Mediocampista" },
    { "name": "Wout Weghorst", "number": 9, "position": "Delantero" },
    { "name": "Memphis Depay", "number": 10, "position": "Delantero" },
    { "name": "Cody Gakpo", "number": 11, "position": "Delantero" },
    { "name": "Mats Wieffer", "number": 12, "position": "Defensa" },
    { "name": "Robin Roefs", "number": 13, "position": "Portero" },
    { "name": "Tijjani Reijnders", "number": 14, "position": "Mediocampista" },
    { "name": "Micky van de Ven", "number": 15, "position": "Defensa" },
    { "name": "Guus Til", "number": 16, "position": "Mediocampista" },
    { "name": "Noa Lang", "number": 17, "position": "Delantero" },
    { "name": "Donyell Malen", "number": 18, "position": "Delantero" },
    { "name": "Brian Brobbey", "number": 19, "position": "Delantero" },
    { "name": "Teun Koopmeiners", "number": 20, "position": "Mediocampista" },
    { "name": "Frenkie de Jong", "number": 21, "position": "Mediocampista" },
    { "name": "Denzel Dumfries", "number": 22, "position": "Defensa" },
    { "name": "Mark Flekken", "number": 23, "position": "Portero" },
    { "name": "Crysencio Summerville", "number": 24, "position": "Delantero" },
    { "name": "Jorrel Hato", "number": 25, "position": "Defensa" },
    { "name": "Quinten Timber", "number": 26, "position": "Mediocampista" }
  ],
  "Noruega": [
    { "name": "Ørjan Nyland", "number": 1, "position": "Portero" },
    { "name": "Morten Thorsby", "number": 2, "position": "Mediocampista" },
    { "name": "Kristoffer Ajer", "number": 3, "position": "Defensa" },
    { "name": "Leo Østigård", "number": 4, "position": "Defensa" },
    { "name": "David Møller Wolfe", "number": 5, "position": "Defensa" },
    { "name": "Patrick Berg", "number": 6, "position": "Mediocampista" },
    { "name": "Alexander Sørloth", "number": 7, "position": "Delantero" },
    { "name": "Sander Berge", "number": 8, "position": "Mediocampista" },
    { "name": "Erling Haaland", "number": 9, "position": "Delantero" },
    { "name": "Martin Ødegaard", "number": 10, "position": "Mediocampista" },
    { "name": "Jørgen Strand Larsen", "number": 11, "position": "Delantero" },
    { "name": "Sander Tangvik", "number": 12, "position": "Portero" },
    { "name": "Egil Selvik", "number": 13, "position": "Portero" },
    { "name": "Fredrik Aursnes", "number": 14, "position": "Mediocampista" },
    { "name": "Fredrik André Bjørkan", "number": 15, "position": "Defensa" },
    { "name": "Marcus Holmgren Pedersen", "number": 16, "position": "Defensa" },
    { "name": "Torbjørn Heggem", "number": 17, "position": "Defensa" },
    { "name": "Kristian Thorstvedt", "number": 18, "position": "Mediocampista" },
    { "name": "Thelo Aasgaard", "number": 19, "position": "Mediocampista" },
    { "name": "Antonio Nusa", "number": 20, "position": "Mediocampista" },
    { "name": "Andreas Schjelderup", "number": 21, "position": "Mediocampista" },
    { "name": "Oscar Bobb", "number": 22, "position": "Mediocampista" },
    { "name": "Jens Petter Hauge", "number": 23, "position": "Mediocampista" },
    { "name": "Sondre Langås", "number": 24, "position": "Defensa" },
    { "name": "Henrik Falchener", "number": 25, "position": "Defensa" },
    { "name": "Julian Ryerson", "number": 26, "position": "Defensa" }
  ],
  "Portugal": [
    { "name": "Diogo Costa", "number": 1, "position": "Portero" },
    { "name": "Nélson Semedo", "number": 2, "position": "Defensa" },
    { "name": "Rúben Dias", "number": 3, "position": "Defensa" },
    { "name": "Tomás Araújo", "number": 4, "position": "Defensa" },
    { "name": "Diogo Dalot", "number": 5, "position": "Defensa" },
    { "name": "Matheus Nunes", "number": 6, "position": "Mediocampista" },
    { "name": "Cristiano Ronaldo", "number": 7, "position": "Delantero" },
    { "name": "Bruno Fernandes", "number": 8, "position": "Mediocampista" },
    { "name": "Gonçalo Ramos", "number": 9, "position": "Delantero" },
    { "name": "Bernardo Silva", "number": 10, "position": "Mediocampista" },
    { "name": "João Félix", "number": 11, "position": "Delantero" },
    { "name": "José Sá", "number": 12, "position": "Portero" },
    { "name": "Renato Veiga", "number": 13, "position": "Defensa" },
    { "name": "Gonçalo Inácio", "number": 14, "position": "Defensa" },
    { "name": "João Neves", "number": 15, "position": "Mediocampista" },
    { "name": "Francisco Trincão", "number": 16, "position": "Delantero" },
    { "name": "Rafael Leão", "number": 17, "position": "Delantero" },
    { "name": "Pedro Neto", "number": 18, "position": "Delantero" },
    { "name": "Gonçalo Guedes", "number": 19, "position": "Delantero" },
    { "name": "João Cancelo", "number": 20, "position": "Defensa" },
    { "name": "Rúben Neves", "number": 21, "position": "Mediocampista" },
    { "name": "Rui Silva", "number": 22, "position": "Portero" },
    { "name": "Vitinha", "number": 23, "position": "Mediocampista" },
    { "name": "Samú Costa", "number": 24, "position": "Defensa" },
    { "name": "Nuno Mendes", "number": 25, "position": "Defensa" },
    { "name": "Francisco Conceição", "number": 26, "position": "Delantero" }
  ],
  "República Checa": [
    { "name": "Matěj Kovář", "number": 1, "position": "Portero" },
    { "name": "David Zima", "number": 2, "position": "Defensa" },
    { "name": "Tomáš Holeš", "number": 3, "position": "Defensa" },
    { "name": "Robin Hranáč", "number": 4, "position": "Defensa" },
    { "name": "Vladimír Coufal", "number": 5, "position": "Defensa" },
    { "name": "Štěpán Chaloupek", "number": 6, "position": "Defensa" },
    { "name": "Ladislav Krejčí", "number": 7, "position": "Defensa" },
    { "name": "Vladimír Darida", "number": 8, "position": "Mediocampista" },
    { "name": "Adam Hložek", "number": 9, "position": "Delantero" },
    { "name": "Patrik Schick", "number": 10, "position": "Delantero" },
    { "name": "Jan Kuchta", "number": 11, "position": "Delantero" },
    { "name": "Lukáš Červ", "number": 12, "position": "Mediocampista" },
    { "name": "Mojmír Chytil", "number": 13, "position": "Delantero" },
    { "name": "David Jurásek", "number": 14, "position": "Defensa" },
    { "name": "Pavel Šulc", "number": 15, "position": "Delantero" },
    { "name": "Jindřich Staněk", "number": 16, "position": "Portero" },
    { "name": "Lukáš Provod", "number": 17, "position": "Mediocampista" },
    { "name": "Michal Sadílek", "number": 18, "position": "Mediocampista" },
    { "name": "Tomáš Chorý", "number": 19, "position": "Delantero" },
    { "name": "Jaroslav Zelený", "number": 20, "position": "Defensa" },
    { "name": "David Douděra", "number": 21, "position": "Defensa" },
    { "name": "Tomáš Souček", "number": 22, "position": "Mediocampista" },
    { "name": "Lukáš Horníček", "number": 23, "position": "Portero" },
    { "name": "Alexandr Sojka", "number": 24, "position": "Mediocampista" },
    { "name": "Hugo Sochůrek", "number": 25, "position": "Mediocampista" },
    { "name": "Denis Višinský", "number": 26, "position": "Delantero" }
  ],
  "Suecia": [
    { "name": "Jacob Widell Zetterström", "number": 1, "position": "Portero" },
    { "name": "Gustaf Lagerbielke", "number": 2, "position": "Defensa" },
    { "name": "Victor Lindelöf", "number": 3, "position": "Defensa" },
    { "name": "Isak Hien", "number": 4, "position": "Defensa" },
    { "name": "Gabriel Gudmundsson", "number": 5, "position": "Defensa" },
    { "name": "Herman Johansson", "number": 6, "position": "Defensa" },
    { "name": "Lucas Bergvall", "number": 7, "position": "Mediocampista" },
    { "name": "Daniel Svensson", "number": 8, "position": "Defensa" },
    { "name": "Alexander Isak", "number": 9, "position": "Delantero" },
    { "name": "Benjamin Nygren", "number": 10, "position": "Mediocampista" },
    { "name": "Anthony Elanga", "number": 11, "position": "Delantero" },
    { "name": "Viktor Johansson", "number": 12, "position": "Portero" },
    { "name": "Ken Sema", "number": 13, "position": "Mediocampista" },
    { "name": "Hjalmar Ekdal", "number": 14, "position": "Defensa" },
    { "name": "Carl Starfelt", "number": 15, "position": "Defensa" },
    { "name": "Jesper Karlström", "number": 16, "position": "Mediocampista" },
    { "name": "Viktor Gyökeres", "number": 17, "position": "Delantero" },
    { "name": "Yasin Ayari", "number": 18, "position": "Mediocampista" },
    { "name": "Mattias Svanberg", "number": 19, "position": "Mediocampista" },
    { "name": "Eric Smith", "number": 20, "position": "Defensa" },
    { "name": "Alexander Bernhardsson", "number": 21, "position": "Defensa" },
    { "name": "Besfort Zeneli", "number": 22, "position": "Mediocampista" },
    { "name": "Kristoffer Nordfeldt", "number": 23, "position": "Portero" },
    { "name": "Elliot Stroud", "number": 24, "position": "Defensa" },
    { "name": "Gustaf Nilsson", "number": 25, "position": "Delantero" },
    { "name": "Taha Ali", "number": 26, "position": "Delantero" }
  ],
  "Suiza": [
    { "name": "Gregor Kobel", "number": 1, "position": "Portero" },
    { "name": "Miro Muheim", "number": 2, "position": "Defensa" },
    { "name": "Silvan Widmer", "number": 3, "position": "Defensa" },
    { "name": "Nico Elvedi", "number": 4, "position": "Defensa" },
    { "name": "Manuel Akanji", "number": 5, "position": "Defensa" },
    { "name": "Denis Zakaria", "number": 6, "position": "Mediocampista" },
    { "name": "Breel Embolo", "number": 7, "position": "Delantero" },
    { "name": "Remo Freuler", "number": 8, "position": "Mediocampista" },
    { "name": "Johan Manzambi", "number": 9, "position": "Mediocampista" },
    { "name": "Granit Xhaka", "number": 10, "position": "Mediocampista" },
    { "name": "Dan Ndoye", "number": 11, "position": "Delantero" },
    { "name": "Yvon Mvogo", "number": 12, "position": "Portero" },
    { "name": "Ricardo Rodriguez", "number": 13, "position": "Defensa" },
    { "name": "Ardon Jashari", "number": 14, "position": "Mediocampista" },
    { "name": "Djibril Sow", "number": 15, "position": "Mediocampista" },
    { "name": "Christian Fassnacht", "number": 16, "position": "Delantero" },
    { "name": "Rubén Vargas", "number": 17, "position": "Delantero" },
    { "name": "Eray Cömert", "number": 18, "position": "Defensa" },
    { "name": "Noah Okafor", "number": 19, "position": "Delantero" },
    { "name": "Michel Aebischer", "number": 20, "position": "Mediocampista" },
    { "name": "Marvin Keller", "number": 21, "position": "Portero" },
    { "name": "Fabian Rieder", "number": 22, "position": "Mediocampista" },
    { "name": "Zeki Amdouni", "number": 23, "position": "Delantero" },
    { "name": "Aurèle Amenda", "number": 24, "position": "Defensa" },
    { "name": "Luca Jaquez", "number": 25, "position": "Defensa" },
    { "name": "Cedric Itten", "number": 26, "position": "Delantero" }
  ],
  "Turquía": [
    { "name": "Mert Günok", "number": 1, "position": "Portero" },
    { "name": "Zeki Çelik", "number": 2, "position": "Defensa" },
    { "name": "Merih Demiral", "number": 3, "position": "Defensa" },
    { "name": "Çağlar Söyüncü", "number": 4, "position": "Defensa" },
    { "name": "Salih Özcan", "number": 5, "position": "Mediocampista" },
    { "name": "Orkun Kökçü", "number": 6, "position": "Mediocampista" },
    { "name": "Kerem Aktürkoğlu", "number": 7, "position": "Delantero" },
    { "name": "Arda Güler", "number": 8, "position": "Delantero" },
    { "name": "Deniz Gül", "number": 9, "position": "Delantero" },
    { "name": "Hakan Çalhanoğlu", "number": 10, "position": "Mediocampista" },
    { "name": "Kenan Yıldız", "number": 11, "position": "Delantero" },
    { "name": "Altay Bayındır", "number": 12, "position": "Portero" },
    { "name": "Eren Elmalı", "number": 13, "position": "Defensa" },
    { "name": "Abdülkerim Bardakcı", "number": 14, "position": "Defensa" },
    { "name": "Ozan Kabak", "number": 15, "position": "Defensa" },
    { "name": "İsmail Yüksek", "number": 16, "position": "Mediocampista" },
    { "name": "İrfan Can Kahveci", "number": 17, "position": "Delantero" },
    { "name": "Mert Müldür", "number": 18, "position": "Defensa" },
    { "name": "Yunus Akgün", "number": 19, "position": "Delantero" },
    { "name": "Ferdi Kadıoğlu", "number": 20, "position": "Defensa" },
    { "name": "Barış Alper Yılmaz", "number": 21, "position": "Delantero" },
    { "name": "Kaan Ayhan", "number": 22, "position": "Mediocampista" },
    { "name": "Uğurcan Çakır", "number": 23, "position": "Portero" },
    { "name": "Oğuz Aydın", "number": 24, "position": "Delantero" },
    { "name": "Samet Akaydin", "number": 25, "position": "Defensa" },
    { "name": "Can Uzun", "number": 26, "position": "Delantero" }
  ],
  "Inglaterra": [
    { "name": "Jordan Pickford", "number": 1, "position": "Portero" },
    { "name": "Ezri Konsa", "number": 2, "position": "Defensa" },
    { "name": "Nico O'Reilly", "number": 3, "position": "Defensa" },
    { "name": "Declan Rice", "number": 4, "position": "Mediocampista" },
    { "name": "John Stones", "number": 5, "position": "Defensa" },
    { "name": "Marc Guéhi", "number": 6, "position": "Defensa" },
    { "name": "Bukayo Saka", "number": 7, "position": "Delantero" },
    { "name": "Elliot Anderson", "number": 8, "position": "Mediocampista" },
    { "name": "Harry Kane", "number": 9, "position": "Delantero" },
    { "name": "Jude Bellingham", "number": 10, "position": "Mediocampista" },
    { "name": "Marcus Rashford", "number": 11, "position": "Delantero" },
    { "name": "Trevoh Chalobah", "number": 12, "position": "Defensa" },
    { "name": "Dean Henderson", "number": 13, "position": "Portero" },
    { "name": "Jordan Henderson", "number": 14, "position": "Mediocampista" },
    { "name": "Dan Burn", "number": 15, "position": "Defensa" },
    { "name": "Kobbie Mainoo", "number": 16, "position": "Mediocampista" },
    { "name": "Morgan Rogers", "number": 17, "position": "Mediocampista" },
    { "name": "Anthony Gordon", "number": 18, "position": "Delantero" },
    { "name": "Ollie Watkins", "number": 19, "position": "Delantero" },
    { "name": "Noni Madueke", "number": 20, "position": "Delantero" },
    { "name": "Eberechi Eze", "number": 21, "position": "Mediocampista" },
    { "name": "Ivan Toney", "number": 22, "position": "Delantero" },
    { "name": "James Trafford", "number": 23, "position": "Portero" },
    { "name": "Reece James", "number": 24, "position": "Defensa" },
    { "name": "Djed Spence", "number": 25, "position": "Defensa" },
    { "name": "Jarell Quansah", "number": 26, "position": "Defensa" }
  ],

  // CAF
  "Argelia": [
    { "name": "Melvin Mastil", "number": 1, "position": "Portero" },
    { "name": "Aïssa Mandi", "number": 2, "position": "Defensa" },
    { "name": "Achref Abada", "number": 3, "position": "Defensa" },
    { "name": "Mohamed Amine Tougai", "number": 4, "position": "Defensa" },
    { "name": "Zineddine Belaïd", "number": 5, "position": "Defensa" },
    { "name": "Ramiz Zerrouki", "number": 6, "position": "Mediocampista" },
    { "name": "Riyad Mahrez", "number": 7, "position": "Delantero" },
    { "name": "Houssem Aouar", "number": 8, "position": "Mediocampista" },
    { "name": "Amine Gouiri", "number": 9, "position": "Delantero" },
    { "name": "Farès Chaïbi", "number": 10, "position": "Mediocampista" },
    { "name": "Anis Hadj Moussa", "number": 11, "position": "Delantero" },
    { "name": "Nadhir Benbouali", "number": 12, "position": "Delantero" },
    { "name": "Jaouen Hadjam", "number": 13, "position": "Defensa" },
    { "name": "Hicham Boudaoui", "number": 14, "position": "Mediocampista" },
    { "name": "Rayan Aït-Nouri", "number": 15, "position": "Defensa" },
    { "name": "Oussama Benbot", "number": 16, "position": "Portero" },
    { "name": "Rafik Belghali", "number": 17, "position": "Defensa" },
    { "name": "Mohamed Amoura", "number": 18, "position": "Delantero" },
    { "name": "Nabil Bentaleb", "number": 19, "position": "Mediocampista" },
    { "name": "Adil Boulbina", "number": 20, "position": "Delantero" },
    { "name": "Ramy Bensebaini", "number": 21, "position": "Defensa" },
    { "name": "Ibrahim Maza", "number": 22, "position": "Mediocampista" },
    { "name": "Luca Zidane", "number": 23, "position": "Portero" },
    { "name": "Yacine Titraoui", "number": 24, "position": "Mediocampista" },
    { "name": "Farès Ghedjemis", "number": 25, "position": "Delantero" },
    { "name": "Samir Chergui", "number": 26, "position": "Defensa" }
  ],
  "Cabo Verde": [
    { "name": "Vozinha", "number": 1, "position": "Portero" },
    { "name": "Stopira", "number": 2, "position": "Defensa" },
    { "name": "Diney", "number": 3, "position": "Defensa" },
    { "name": "Pico Lopes", "number": 4, "position": "Defensa" },
    { "name": "Logan Costa", "number": 5, "position": "Defensa" },
    { "name": "Kevin Pina", "number": 6, "position": "Mediocampista" },
    { "name": "Jovane Cabral", "number": 7, "position": "Mediocampista" },
    { "name": "João Paulo Fernandes", "number": 8, "position": "Mediocampista" },
    { "name": "Gilson Benchimol", "number": 9, "position": "Delantero" },
    { "name": "Jamiro Monteiro", "number": 10, "position": "Mediocampista" },
    { "name": "Garry Rodrigues", "number": 11, "position": "Mediocampista" },
    { "name": "Mário Rosa", "number": 12, "position": "Portero" },
    { "name": "Sidny Lopes Cabral", "number": 13, "position": "Defensa" },
    { "name": "Deroy Duarte", "number": 14, "position": "Mediocampista" },
    { "name": "Laros Duarte", "number": 15, "position": "Mediocampista" },
    { "name": "Yannick Semedo", "number": 16, "position": "Mediocampista" },
    { "name": "Willy Semedo", "number": 17, "position": "Mediocampista" },
    { "name": "Telmo Arcanjo", "number": 18, "position": "Mediocampista" },
    { "name": "Dailon Livramento", "number": 19, "position": "Delantero" },
    { "name": "Ryan Mendes", "number": 20, "position": "Delantero" },
    { "name": "Nuno da Costa", "number": 21, "position": "Mediocampista" },
    { "name": "Steven Moreira", "number": 22, "position": "Defensa" },
    { "name": "CJ dos Santos", "number": 23, "position": "Portero" },
    { "name": "Wagner Pina", "number": 24, "position": "Defensa" },
    { "name": "Kelvin Pires", "number": 25, "position": "Defensa" },
    { "name": "Hélio Varela", "number": 26, "position": "Mediocampista" }
  ],
  "Costa de Marfil": [
    { "name": "Yahia Fofana", "number": 1, "position": "Portero" },
    { "name": "Ousmane Diomande", "number": 2, "position": "Defensa" },
    { "name": "Ghislain Konan", "number": 3, "position": "Defensa" },
    { "name": "Jean Michaël Seri", "number": 4, "position": "Mediocampista" },
    { "name": "Wilfried Singo", "number": 5, "position": "Defensa" },
    { "name": "Seko Fofana", "number": 6, "position": "Mediocampista" },
    { "name": "Odilon Kossounou", "number": 7, "position": "Defensa" },
    { "name": "Franck Kessié", "number": 8, "position": "Mediocampista" },
    { "name": "Ange-Yoan Bonny", "number": 9, "position": "Delantero" },
    { "name": "Simon Adingra", "number": 10, "position": "Delantero" },
    { "name": "Yan Diomande", "number": 11, "position": "Delantero" },
    { "name": "Elye Wahi", "number": 12, "position": "Delantero" },
    { "name": "Christopher Opéri", "number": 13, "position": "Defensa" },
    { "name": "Oumar Diakité", "number": 14, "position": "Delantero" },
    { "name": "Amad Diallo", "number": 15, "position": "Delantero" },
    { "name": "Mohamed Koné", "number": 16, "position": "Portero" },
    { "name": "Guéla Doué", "number": 17, "position": "Defensa" },
    { "name": "Ibrahim Sangaré", "number": 18, "position": "Mediocampista" },
    { "name": "Nicolas Pépé", "number": 19, "position": "Delantero" },
    { "name": "Emmanuel Agbadou", "number": 20, "position": "Defensa" },
    { "name": "Evan Ndicka", "number": 21, "position": "Defensa" },
    { "name": "Evann Guessand", "number": 22, "position": "Delantero" },
    { "name": "Alban Lafont", "number": 23, "position": "Portero" },
    { "name": "Bazoumana Touré", "number": 24, "position": "Delantero" },
    { "name": "Parfait Guiagon", "number": 25, "position": "Mediocampista" },
    { "name": "Christ Inao Oulaïf", "number": 26, "position": "Mediocampista" }
  ],
  "Egipto": [
    { "name": "Mohamed El Shenawy", "number": 1, "position": "Portero" },
    { "name": "Yasser Ibrahim", "number": 2, "position": "Defensa" },
    { "name": "Mohamed Hany", "number": 3, "position": "Defensa" },
    { "name": "Hossam Abdelmaguid", "number": 4, "position": "Defensa" },
    { "name": "Ramy Rabia", "number": 5, "position": "Defensa" },
    { "name": "Mohamed Abdelmonem", "number": 6, "position": "Defensa" },
    { "name": "Trézéguet", "number": 7, "position": "Delantero" },
    { "name": "Emam Ashour", "number": 8, "position": "Mediocampista" },
    { "name": "Hamza Abdelkarim", "number": 9, "position": "Delantero" },
    { "name": "Mohamed Salah", "number": 10, "position": "Delantero" },
    { "name": "Mostafa Ziko", "number": 11, "position": "Mediocampista" },
    { "name": "Haissem Hassan", "number": 12, "position": "Delantero" },
    { "name": "Ahmed Fatouh", "number": 13, "position": "Defensa" },
    { "name": "Hamdy Fathy", "number": 14, "position": "Mediocampista" },
    { "name": "Karim Hafez", "number": 15, "position": "Defensa" },
    { "name": "El Mahdy Soliman", "number": 16, "position": "Portero" },
    { "name": "Mohanad Lasheen", "number": 17, "position": "Mediocampista" },
    { "name": "Nabil Emad", "number": 18, "position": "Mediocampista" },
    { "name": "Marwan Attia", "number": 19, "position": "Mediocampista" },
    { "name": "Ibrahim Adel", "number": 20, "position": "Delantero" },
    { "name": "Mahmoud Saber", "number": 21, "position": "Mediocampista" },
    { "name": "Omar Marmoush", "number": 22, "position": "Delantero" },
    { "name": "Mostafa Shobeir", "number": 23, "position": "Portero" },
    { "name": "Tarek Alaa", "number": 24, "position": "Defensa" },
    { "name": "Zizo", "number": 25, "position": "Delantero" },
    { "name": "Mohamed Alaa", "number": 26, "position": "Portero" }
  ],
  "Ghana": [
    { "name": "Lawrence Ati-Zigi", "number": 1, "position": "Portero" },
    { "name": "Alidu Seidu", "number": 2, "position": "Defensa" },
    { "name": "Caleb Yirenkyi", "number": 3, "position": "Mediocampista" },
    { "name": "Jonas Adjetey", "number": 4, "position": "Defensa" },
    { "name": "Thomas Partey", "number": 5, "position": "Mediocampista" },
    { "name": "Abdul Mumin", "number": 6, "position": "Defensa" },
    { "name": "Abdul Fatawu", "number": 7, "position": "Delantero" },
    { "name": "Kwasi Sibo", "number": 8, "position": "Mediocampista" },
    { "name": "Jordan Ayew", "number": 9, "position": "Delantero" },
    { "name": "Brandon Thomas-Asante", "number": 10, "position": "Delantero" },
    { "name": "Antoine Semenyo", "number": 11, "position": "Mediocampista" },
    { "name": "Joseph Anang", "number": 12, "position": "Portero" },
    { "name": "Christopher Bonsu Baah", "number": 13, "position": "Delantero" },
    { "name": "Gideon Mensah", "number": 14, "position": "Defensa" },
    { "name": "Elisha Owusu", "number": 15, "position": "Mediocampista" },
    { "name": "Benjamin Asare", "number": 16, "position": "Portero" },
    { "name": "Abdul Rahman Baba", "number": 17, "position": "Defensa" },
    { "name": "Jerome Opoku", "number": 18, "position": "Defensa" },
    { "name": "Iñaki Williams", "number": 19, "position": "Delantero" },
    { "name": "Augustine Boakye", "number": 20, "position": "Mediocampista" },
    { "name": "Kojo Peprah Oppong", "number": 21, "position": "Defensa" },
    { "name": "Kamaldeen Sulemana", "number": 22, "position": "Delantero" },
    { "name": "Derrick Luckassen", "number": 23, "position": "Defensa" },
    { "name": "Ernest Nuamah", "number": 24, "position": "Delantero" },
    { "name": "Prince Kwabena Adu", "number": 25, "position": "Delantero" },
    { "name": "Marvin Senaya", "number": 26, "position": "Defensa" }
  ],
  "Marruecos": [
    { "name": "Yassine Bounou", "number": 1, "position": "Portero" },
    { "name": "Achraf Hakimi", "number": 2, "position": "Defensa" },
    { "name": "Noussair Mazraoui", "number": 3, "position": "Defensa" },
    { "name": "Sofyan Amrabat", "number": 4, "position": "Mediocampista" },
    { "name": "Marwane Saâdane", "number": 5, "position": "Defensa" },
    { "name": "Ayyoub Bouaddi", "number": 6, "position": "Mediocampista" },
    { "name": "Chemsdine Talbi", "number": 7, "position": "Mediocampista" },
    { "name": "Azzedine Ounahi", "number": 8, "position": "Mediocampista" },
    { "name": "Soufiane Rahimi", "number": 9, "position": "Delantero" },
    { "name": "Brahim Díaz", "number": 10, "position": "Delantero" },
    { "name": "Ismael Saibari", "number": 11, "position": "Mediocampista" },
    { "name": "Munir Mohamedi", "number": 12, "position": "Portero" },
    { "name": "Zakaria El Ouahdi", "number": 13, "position": "Defensa" },
    { "name": "Issa Diop", "number": 14, "position": "Defensa" },
    { "name": "Samir El Mourabet", "number": 15, "position": "Mediocampista" },
    { "name": "Gessime Yassine", "number": 16, "position": "Mediocampista" },
    { "name": "Amine Sbaïf", "number": 17, "position": "Delantero" },
    { "name": "Chadi Riad", "number": 18, "position": "Defensa" },
    { "name": "Youssef Belammari", "number": 19, "position": "Defensa" },
    { "name": "Ayoub El Kaabi", "number": 20, "position": "Delantero" },
    { "name": "Ayoube Amaimouni", "number": 21, "position": "Delantero" },
    { "name": "Ahmed Reda Tagnaouti", "number": 22, "position": "Portero" },
    { "name": "Bilal El Khannouss", "number": 23, "position": "Mediocampista" },
    { "name": "Neil El Aynaoui", "number": 24, "position": "Mediocampista" },
    { "name": "Redouane Halhal", "number": 25, "position": "Defensa" },
    { "name": "Anass Salah-Eddine", "number": 26, "position": "Defensa" }
  ],
  "RD del Congo": [
    { "name": "Lionel Mpasi", "number": 1, "position": "Portero" },
    { "name": "Aaron Wan-Bissaka", "number": 2, "position": "Defensa" },
    { "name": "Steve Kapuadi", "number": 3, "position": "Defensa" },
    { "name": "Axel Tuanzebe", "number": 4, "position": "Defensa" },
    { "name": "Dylan Batubinsika", "number": 5, "position": "Defensa" },
    { "name": "Ngal'ayel Mukau", "number": 6, "position": "Mediocampista" },
    { "name": "Nathanaël Mbuku", "number": 7, "position": "Mediocampista" },
    { "name": "Samuel Moutoussamy", "number": 8, "position": "Mediocampista" },
    { "name": "Brian Cipenga", "number": 9, "position": "Delantero" },
    { "name": "Théo Bongonda", "number": 10, "position": "Mediocampista" },
    { "name": "Gaël Kakuta", "number": 11, "position": "Delantero" },
    { "name": "Joris Kayembe", "number": 12, "position": "Defensa" },
    { "name": "Meschak Elia", "number": 13, "position": "Delantero" },
    { "name": "Noah Sadiki", "number": 14, "position": "Mediocampista" },
    { "name": "Aaron Tshibola", "number": 15, "position": "Mediocampista" },
    { "name": "Timothy Fayulu", "number": 16, "position": "Portero" },
    { "name": "Cédric Bakambu", "number": 17, "position": "Delantero" },
    { "name": "Charles Pickel", "number": 18, "position": "Mediocampista" },
    { "name": "Fiston Mayele", "number": 19, "position": "Delantero" },
    { "name": "Yoane Wissa", "number": 20, "position": "Delantero" },
    { "name": "Matthieu Epolo", "number": 21, "position": "Portero" },
    { "name": "Chancel Mbemba", "number": 22, "position": "Defensa" },
    { "name": "Simon Banza", "number": 23, "position": "Delantero" },
    { "name": "Gédéon Kalulu", "number": 24, "position": "Defensa" },
    { "name": "Edo Kayembe", "number": 25, "position": "Mediocampista" },
    { "name": "Arthur Masuaku", "number": 26, "position": "Defensa" }
  ],
  "Senegal": [
    { "name": "Yehvann Diouf", "number": 1, "position": "Portero" },
    { "name": "Mamadou Sarr", "number": 2, "position": "Defensa" },
    { "name": "Kalidou Koulibaly", "number": 3, "position": "Defensa" },
    { "name": "Abdoulaye Seck", "number": 4, "position": "Defensa" },
    { "name": "Idrissa Gueye", "number": 5, "position": "Mediocampista" },
    { "name": "Pathé Ciss", "number": 6, "position": "Mediocampista" },
    { "name": "Assane Diao", "number": 7, "position": "Delantero" },
    { "name": "Lamine Camara", "number": 8, "position": "Mediocampista" },
    { "name": "Bamba Dieng", "number": 9, "position": "Delantero" },
    { "name": "Sadio Mané", "number": 10, "position": "Delantero" },
    { "name": "Nicolas Jackson", "number": 11, "position": "Delantero" },
    { "name": "Cherif Ndiaye", "number": 12, "position": "Delantero" },
    { "name": "Iliman Ndiaye", "number": 13, "position": "Delantero" },
    { "name": "Ismail Jakobs", "number": 14, "position": "Defensa" },
    { "name": "Krépin Diatta", "number": 15, "position": "Defensa" },
    { "name": "Édouard Mendy", "number": 16, "position": "Portero" },
    { "name": "Pape Matar Sarr", "number": 17, "position": "Mediocampista" },
    { "name": "Ismaïla Sarr", "number": 18, "position": "Delantero" },
    { "name": "Moussa Niakhaté", "number": 19, "position": "Defensa" },
    { "name": "Ibrahim Mbaye", "number": 20, "position": "Delantero" },
    { "name": "Habib Diarra", "number": 21, "position": "Mediocampista" },
    { "name": "Bara Sapoko Ndiaye", "number": 22, "position": "Mediocampista" },
    { "name": "Mory Diaw", "number": 23, "position": "Portero" },
    { "name": "Antoine Mendy", "number": 24, "position": "Defensa" },
    { "name": "El Hadji Malick Diouf", "number": 25, "position": "Defensa" },
    { "name": "Pape Gueye", "number": 26, "position": "Mediocampista" }
  ],
  "Sudáfrica": [
    { "name": "Ronwen Williams", "number": 1, "position": "Portero" },
    { "name": "Thabang Matuludi", "number": 2, "position": "Defensa" },
    { "name": "Khulumani Ndamane", "number": 3, "position": "Defensa" },
    { "name": "Teboho Mokoena", "number": 4, "position": "Mediocampista" },
    { "name": "Thalente Mbatha", "number": 5, "position": "Mediocampista" },
    { "name": "Aubrey Modiba", "number": 6, "position": "Defensa" },
    { "name": "Oswin Appollis", "number": 7, "position": "Delantero" },
    { "name": "Tshepang Moremi", "number": 8, "position": "Delantero" },
    { "name": "Lyle Foster", "number": 9, "position": "Delantero" },
    { "name": "Relebohile Mofokeng", "number": 10, "position": "Delantero" },
    { "name": "Themba Zwane", "number": 11, "position": "Mediocampista" },
    { "name": "Thapelo Maseko", "number": 12, "position": "Delantero" },
    { "name": "Sphephelo Sithole", "number": 13, "position": "Mediocampista" },
    { "name": "Mbekezeli Mbokazi", "number": 14, "position": "Defensa" },
    { "name": "Iqraam Rayners", "number": 15, "position": "Delantero" },
    { "name": "Sipho Chaine", "number": 16, "position": "Portero" },
    { "name": "Evidence Makgopa", "number": 17, "position": "Delantero" },
    { "name": "Samukele Kabini", "number": 18, "position": "Defensa" },
    { "name": "Nkosinathi Sibisi", "number": 19, "position": "Defensa" },
    { "name": "Khuliso Mudau", "number": 20, "position": "Defensa" },
    { "name": "Ime Okon", "number": 21, "position": "Defensa" },
    { "name": "Ricardo Goss", "number": 22, "position": "Portero" },
    { "name": "Jayden Adams", "number": 23, "position": "Mediocampista" },
    { "name": "Olwethu Makhanya", "number": 24, "position": "Defensa" },
    { "name": "Kamogelo Sebelebele", "number": 25, "position": "Delantero" },
    { "name": "Bradley Cross", "number": 26, "position": "Defensa" }
  ],
  "Túnez": [
    { "name": "Mouhib Chamakh", "number": 1, "position": "Portero" },
    { "name": "Ali Abdi", "number": 2, "position": "Defensa" },
    { "name": "Montassar Talbi", "number": 3, "position": "Defensa" },
    { "name": "Omar Rekik", "number": 4, "position": "Defensa" },
    { "name": "Adem Arous", "number": 5, "position": "Defensa" },
    { "name": "Dylan Bronn", "number": 6, "position": "Defensa" },
    { "name": "Elias Achouri", "number": 7, "position": "Delantero" },
    { "name": "Elias Saad", "number": 8, "position": "Delantero" },
    { "name": "Hazem Mastouri", "number": 9, "position": "Delantero" },
    { "name": "Hannibal Mejbri", "number": 10, "position": "Mediocampista" },
    { "name": "Ismaël Gharbi", "number": 11, "position": "Mediocampista" },
    { "name": "Mortadha Ben Ouanes", "number": 12, "position": "Defensa" },
    { "name": "Rani Khedira", "number": 13, "position": "Mediocampista" },
    { "name": "Khalil Ayari", "number": 14, "position": "Mediocampista" },
    { "name": "Mohamed Belhadj Mahmoud", "number": 15, "position": "Mediocampista" },
    { "name": "Aymen Dahmen", "number": 16, "position": "Portero" },
    { "name": "Ellyes Skhiri", "number": 17, "position": "Mediocampista" },
    { "name": "Rayan Elloumi", "number": 18, "position": "Delantero" },
    { "name": "Firas Chaouat", "number": 19, "position": "Delantero" },
    { "name": "Yan Valery", "number": 20, "position": "Defensa" },
    { "name": "Mohamed Amine Ben Hamida", "number": 21, "position": "Defensa" },
    { "name": "Sabri Ben Hessen", "number": 22, "position": "Portero" },
    { "name": "Moutaz Neffati", "number": 23, "position": "Defensa" },
    { "name": "Raed Chikhaoui", "number": 24, "position": "Defensa" },
    { "name": "Anis Ben Slimane", "number": 25, "position": "Mediocampista" },
    { "name": "Sebastian Tounekti", "number": 26, "position": "Mediocampista" }
  ],

  // CONCACAF + OFC
  "Canadá": [
    { "name": "Dayne St. Clair", "number": 1, "position": "Portero" },
    { "name": "Alistair Johnston", "number": 2, "position": "Defensa" },
    { "name": "Alfie Jones", "number": 3, "position": "Defensa" },
    { "name": "Luc de Fougerolles", "number": 4, "position": "Defensa" },
    { "name": "Joel Waterman", "number": 5, "position": "Defensa" },
    { "name": "Mathieu Choinière", "number": 6, "position": "Mediocampista" },
    { "name": "Stephen Eustáquio", "number": 7, "position": "Mediocampista" },
    { "name": "Ismaël Koné", "number": 8, "position": "Mediocampista" },
    { "name": "Cyle Larin", "number": 9, "position": "Delantero" },
    { "name": "Jonathan David", "number": 10, "position": "Delantero" },
    { "name": "Liam Millar", "number": 11, "position": "Mediocampista" },
    { "name": "Tani Oluwaseyi", "number": 12, "position": "Delantero" },
    { "name": "Derek Cornelius", "number": 13, "position": "Defensa" },
    { "name": "Jacob Shaffelburg", "number": 14, "position": "Mediocampista" },
    { "name": "Moïse Bombito", "number": 15, "position": "Defensa" },
    { "name": "Maxime Crépeau", "number": 16, "position": "Portero" },
    { "name": "Tajon Buchanan", "number": 17, "position": "Delantero" },
    { "name": "Owen Goodman", "number": 18, "position": "Portero" },
    { "name": "Alphonso Davies", "number": 19, "position": "Defensa" },
    { "name": "Ali Ahmed", "number": 20, "position": "Delantero" },
    { "name": "Jonathan Osorio", "number": 21, "position": "Mediocampista" },
    { "name": "Richie Laryea", "number": 22, "position": "Defensa" },
    { "name": "Niko Sigur", "number": 23, "position": "Defensa" },
    { "name": "Promise David", "number": 24, "position": "Delantero" },
    { "name": "Nathan Saliba", "number": 25, "position": "Mediocampista" },
    { "name": "Jayden Nelson", "number": 26, "position": "Delantero" }
  ],
  "Curazao": [
    { "name": "Eloy Room", "number": 1, "position": "Portero" },
    { "name": "Shurandy Sambo", "number": 2, "position": "Defensa" },
    { "name": "Jurién Gaari", "number": 3, "position": "Defensa" },
    { "name": "Roshon van Eijma", "number": 4, "position": "Defensa" },
    { "name": "Sherel Floranus", "number": 5, "position": "Defensa" },
    { "name": "Godfried Roemeratoe", "number": 6, "position": "Mediocampista" },
    { "name": "Juninho Bacuna", "number": 7, "position": "Mediocampista" },
    { "name": "Livano Comenencia", "number": 8, "position": "Mediocampista" },
    { "name": "Jürgen Locadia", "number": 9, "position": "Delantero" },
    { "name": "Leandro Bacuna", "number": 10, "position": "Mediocampista" },
    { "name": "Jeremy Antonisse", "number": 11, "position": "Delantero" },
    { "name": "Sontje Hansen", "number": 12, "position": "Delantero" },
    { "name": "Tyrese Noslin", "number": 13, "position": "Delantero" },
    { "name": "Kenji Gorré", "number": 14, "position": "Delantero" },
    { "name": "Ar'jany Martha", "number": 15, "position": "Mediocampista" },
    { "name": "Jearl Margaritha", "number": 16, "position": "Delantero" },
    { "name": "Brandley Kuwas", "number": 17, "position": "Delantero" },
    { "name": "Armando Obispo", "number": 18, "position": "Defensa" },
    { "name": "Gervane Kastaneer", "number": 19, "position": "Delantero" },
    { "name": "Joshua Brenet", "number": 20, "position": "Defensa" },
    { "name": "Tahith Chong", "number": 21, "position": "Mediocampista" },
    { "name": "Kevin Felida", "number": 22, "position": "Mediocampista" },
    { "name": "Riechedly Bazoer", "number": 23, "position": "Defensa" },
    { "name": "Deveron Fonville", "number": 24, "position": "Defensa" },
    { "name": "Tyrick Bodak", "number": 25, "position": "Portero" },
    { "name": "Trevor Doornbusch", "number": 26, "position": "Portero" }
  ],
  "Estados Unidos": [
    { "name": "Matt Turner", "number": 1, "position": "Portero" },
    { "name": "Sergiño Dest", "number": 2, "position": "Defensa" },
    { "name": "Chris Richards", "number": 3, "position": "Defensa" },
    { "name": "Tyler Adams", "number": 4, "position": "Mediocampista" },
    { "name": "Antonee Robinson", "number": 5, "position": "Defensa" },
    { "name": "Auston Trusty", "number": 6, "position": "Defensa" },
    { "name": "Giovanni Reyna", "number": 7, "position": "Mediocampista" },
    { "name": "Weston McKennie", "number": 8, "position": "Mediocampista" },
    { "name": "Ricardo Pepi", "number": 9, "position": "Delantero" },
    { "name": "Christian Pulisic", "number": 10, "position": "Delantero" },
    { "name": "Brenden Aaronson", "number": 11, "position": "Delantero" },
    { "name": "Miles Robinson", "number": 12, "position": "Defensa" },
    { "name": "Tim Ream", "number": 13, "position": "Defensa" },
    { "name": "Sebastian Berhalter", "number": 14, "position": "Mediocampista" },
    { "name": "Cristian Roldan", "number": 15, "position": "Mediocampista" },
    { "name": "Alex Freeman", "number": 16, "position": "Defensa" },
    { "name": "Malik Tillman", "number": 17, "position": "Mediocampista" },
    { "name": "Max Arfsten", "number": 18, "position": "Defensa" },
    { "name": "Haji Wright", "number": 19, "position": "Delantero" },
    { "name": "Folarin Balogun", "number": 20, "position": "Delantero" },
    { "name": "Timothy Weah", "number": 21, "position": "Delantero" },
    { "name": "Mark McKenzie", "number": 22, "position": "Defensa" },
    { "name": "Joe Scally", "number": 23, "position": "Defensa" },
    { "name": "Matt Freese", "number": 24, "position": "Portero" },
    { "name": "Chris Brady", "number": 25, "position": "Portero" },
    { "name": "Alejandro Zendejas", "number": 26, "position": "Delantero" }
  ],
  "Haití": [
    { "name": "Johny Placide", "number": 1, "position": "Portero" },
    { "name": "Carlens Arcus", "number": 2, "position": "Defensa" },
    { "name": "Keeto Thermoncy", "number": 3, "position": "Defensa" },
    { "name": "Ricardo Adé", "number": 4, "position": "Defensa" },
    { "name": "Hannes Delcroix", "number": 5, "position": "Defensa" },
    { "name": "Carl Sainté", "number": 6, "position": "Mediocampista" },
    { "name": "Derrick Etienne Jr.", "number": 7, "position": "Delantero" },
    { "name": "Martin Expérience", "number": 8, "position": "Defensa" },
    { "name": "Duckens Nazon", "number": 9, "position": "Delantero" },
    { "name": "Jean-Ricner Bellegarde", "number": 10, "position": "Mediocampista" },
    { "name": "Louicius Deedson", "number": 11, "position": "Delantero" },
    { "name": "Alexandre Pierre", "number": 12, "position": "Portero" },
    { "name": "Duke Lacroix", "number": 13, "position": "Defensa" },
    { "name": "Garven Metusala", "number": 14, "position": "Defensa" },
    { "name": "Ruben Providence", "number": 15, "position": "Delantero" },
    { "name": "Lenny Joseph", "number": 16, "position": "Delantero" },
    { "name": "Danley Jean Jacques", "number": 17, "position": "Mediocampista" },
    { "name": "Wilson Isidor", "number": 18, "position": "Delantero" },
    { "name": "Yassin Fortuné", "number": 19, "position": "Delantero" },
    { "name": "Frantzdy Pierrot", "number": 20, "position": "Delantero" },
    { "name": "Josué Casimir", "number": 21, "position": "Delantero" },
    { "name": "Jean-Kévin Duverne", "number": 22, "position": "Defensa" },
    { "name": "Josué Duverger", "number": 23, "position": "Portero" },
    { "name": "Wilguens Paugain", "number": 24, "position": "Defensa" },
    { "name": "Dominique Simon", "number": 25, "position": "Mediocampista" },
    { "name": "Woodensky Pierre", "number": 26, "position": "Mediocampista" }
  ],
  "México": [
    { "name": "Raúl Rangel", "number": 1, "position": "Portero" },
    { "name": "Jorge Sánchez", "number": 2, "position": "Defensa" },
    { "name": "César Montes", "number": 3, "position": "Defensa" },
    { "name": "Edson Álvarez", "number": 4, "position": "Defensa" },
    { "name": "Johan Vásquez", "number": 5, "position": "Defensa" },
    { "name": "Érik Lira", "number": 6, "position": "Mediocampista" },
    { "name": "Luis Romo", "number": 7, "position": "Mediocampista" },
    { "name": "Álvaro Fidalgo", "number": 8, "position": "Mediocampista" },
    { "name": "Raúl Jiménez", "number": 9, "position": "Delantero" },
    { "name": "Alexis Vega", "number": 10, "position": "Delantero" },
    { "name": "Santiago Giménez", "number": 11, "position": "Delantero" },
    { "name": "Carlos Acevedo", "number": 12, "position": "Portero" },
    { "name": "Guillermo Ochoa", "number": 13, "position": "Portero" },
    { "name": "Armando González", "number": 14, "position": "Delantero" },
    { "name": "Israel Reyes", "number": 15, "position": "Defensa" },
    { "name": "Julián Quiñones", "number": 16, "position": "Delantero" },
    { "name": "Orbelín Pineda", "number": 17, "position": "Mediocampista" },
    { "name": "Obed Vargas", "number": 18, "position": "Mediocampista" },
    { "name": "Gilberto Mora", "number": 19, "position": "Mediocampista" },
    { "name": "Mateo Chávez", "number": 20, "position": "Defensa" },
    { "name": "César Huerta", "number": 21, "position": "Delantero" },
    { "name": "Guillermo Martínez", "number": 22, "position": "Delantero" },
    { "name": "Jesús Gallardo", "number": 23, "position": "Defensa" },
    { "name": "Luis Chávez", "number": 24, "position": "Mediocampista" },
    { "name": "Roberto Alvarado", "number": 25, "position": "Delantero" },
    { "name": "Brian Gutiérrez", "number": 26, "position": "Mediocampista" }
  ],
  "Panamá": [
    { "name": "Luis Mejía", "number": 1, "position": "Portero" },
    { "name": "César Blackman", "number": 2, "position": "Defensa" },
    { "name": "José Córdoba", "number": 3, "position": "Defensa" },
    { "name": "Fidel Escobar", "number": 4, "position": "Defensa" },
    { "name": "Edgardo Fariña", "number": 5, "position": "Defensa" },
    { "name": "Cristian Martínez", "number": 6, "position": "Mediocampista" },
    { "name": "José Luis Rodríguez", "number": 7, "position": "Mediocampista" },
    { "name": "Adalberto Carrasquilla", "number": 8, "position": "Mediocampista" },
    { "name": "Tomás Rodríguez", "number": 9, "position": "Delantero" },
    { "name": "Ismael Díaz", "number": 10, "position": "Mediocampista" },
    { "name": "Yoel Bárcenas", "number": 11, "position": "Mediocampista" },
    { "name": "César Samudio", "number": 12, "position": "Portero" },
    { "name": "Jiovany Ramos", "number": 13, "position": "Defensa" },
    { "name": "Carlos Harvey", "number": 14, "position": "Defensa" },
    { "name": "Eric Davis", "number": 15, "position": "Defensa" },
    { "name": "Andrés Andrade", "number": 16, "position": "Defensa" },
    { "name": "José Fajardo", "number": 17, "position": "Delantero" },
    { "name": "Cecilio Waterman", "number": 18, "position": "Delantero" },
    { "name": "Alberto Quintero", "number": 19, "position": "Mediocampista" },
    { "name": "Aníbal Godoy", "number": 20, "position": "Mediocampista" },
    { "name": "César Yanis", "number": 21, "position": "Mediocampista" },
    { "name": "Orlando Mosquera", "number": 22, "position": "Portero" },
    { "name": "Michael Amir Murillo", "number": 23, "position": "Defensa" },
    { "name": "Azarias Londoño", "number": 24, "position": "Delantero" },
    { "name": "Roderick Miller", "number": 25, "position": "Defensa" },
    { "name": "Jorge Gutiérrez", "number": 26, "position": "Defensa" }
  ],
  "Nueva Zelanda": [
    { "name": "Max Crocombe", "number": 1, "position": "Portero" },
    { "name": "Tim Payne", "number": 2, "position": "Defensa" },
    { "name": "Francis de Vries", "number": 3, "position": "Defensa" },
    { "name": "Tyler Bindon", "number": 4, "position": "Defensa" },
    { "name": "Michael Boxall", "number": 5, "position": "Defensa" },
    { "name": "Joe Bell", "number": 6, "position": "Mediocampista" },
    { "name": "Logan Rogerson", "number": 7, "position": "Delantero" },
    { "name": "Marko Stamenić", "number": 8, "position": "Mediocampista" },
    { "name": "Chris Wood", "number": 9, "position": "Delantero" },
    { "name": "Sarpreet Singh", "number": 10, "position": "Mediocampista" },
    { "name": "Elijah Just", "number": 11, "position": "Mediocampista" },
    { "name": "Alex Paulsen", "number": 12, "position": "Portero" },
    { "name": "Liberato Cacace", "number": 13, "position": "Defensa" },
    { "name": "Alex Rufer", "number": 14, "position": "Mediocampista" },
    { "name": "Nando Pijnaker", "number": 15, "position": "Defensa" },
    { "name": "Finn Surman", "number": 16, "position": "Defensa" },
    { "name": "Kosta Barbarouses", "number": 17, "position": "Delantero" },
    { "name": "Ben Waine", "number": 18, "position": "Delantero" },
    { "name": "Ben Old", "number": 19, "position": "Mediocampista" },
    { "name": "Callum McCowatt", "number": 20, "position": "Mediocampista" },
    { "name": "Jesse Randall", "number": 21, "position": "Delantero" },
    { "name": "Michael Woud", "number": 22, "position": "Portero" },
    { "name": "Ryan Thomas", "number": 23, "position": "Mediocampista" },
    { "name": "Callan Elliot", "number": 24, "position": "Defensa" },
    { "name": "Lachlan Bayliss", "number": 25, "position": "Mediocampista" },
    { "name": "Tommy Smith", "number": 26, "position": "Defensa" }
  ]
}
